# Nome dell'applicazione
spring.application.name=MyFinBank

# Porta del server
server.port=8080

# Configurazione del database Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=fin_user
spring.datasource.password=fin_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#Per utilizzzare DB reale nei test
spring.test.database.replace=NONE

# Dialettica JPA/hibernate per Oracle DB
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logback attivato
logging.config=classpath:logback-spring.xml

# Livello predefinito (puo essere configurato anche dinamicamente nel codice)
logging.level.root=INFO
logging.file.name=logs/application.log
logging.file.max-size=10MB
logging.file.max-history=30

# Profilo attivo
spring.profiles.active=test

# Configurazione Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs

# Logging per SpringDoc e Swagger
logging.level.org.springdoc=DEBUG
logging.level.org.springdoc.api=DEBUG
logging.level.org.springdoc.api.OpenApiResource=TRACE

#Log per debug
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

#Scadenza token
app.jwt.secret=replace_this_with_a_strong_secret_at_least_32_bytes_long_!
app.jwt.accessTokenExpirationMs=900000
app.jwt.refreshTokenExpirationMs=1209600000

