# Nome dell'applicazione
spring.application.name=MyFinBank

# Porta del server
server.port=8080

# Configurazione del database Oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=fin_user
spring.datasource.password=fin_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Dialettica JPA/hibernate per Oracle DB
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Profilo attivo
spring.profiles.active=dev

# Configurazione Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs

#Log per debug
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
